### ISSUE TITLE
Moderators unable to see public channel name users want to post anon message to.

### ISSUE THREAD

**Issue by cristinaveale** [kevin-wynn/fifthbot-issues#4]
### Prerequisites

- [Yes ] Is this issue reproducible on the current live version?
- [No ] Does this issue expose security risks?
- [No ] Do you get any errors from the app? 

### Description

[When a user tries to post a message in a channel, the channel name is not present under the FifthBot App section. Ex: "A user wants to send an anonymous message in #" ]

### Steps to Reproduce

1. [Use /fifthbot command to type a message in a channel]
2. [As a moderator, under Apps > FifthBot, view message. You'll see: `A user wants to send an anonymous message in #` ]
3. [Unable to view what public channel user wishes to post in]

**Expected behavior:** [A user wants to send an anonymous message in #general]

**Actual behavior:** [A user wants to send an anonymous message in #]

**Comment by kevin-wynn** [comment]
Hi @cristinaveale I saw this bug come up while I was working on some updates for v2 of the app. However I do have some unfortunate news, its come to my attention that fifthbot is being used for reasons other than what I had originally designed and created it for. And it crosses an ethical line that I am uncomfortable with. It was never my intention to create something that could be used to cause others pain so with that being said. As of today I'm going to be shutting down fifthbot for the time being.

I along with another dev are working on huge improvements for the app and we plan on adding some profanity and abuse filtering in. As well as scoping to text only, no more links, no more images will be shareable through fifthbot. This will help force users to use fifthbot as intended, for transparency in companies instead of abuse to users in a shared slack organization.

Keep an eye out for Rakkoon as it will be coming along in the next few months and will have WAY more to offer!
